# RoomRTC Configuration File

[network]
# IP address to bind sockets to. 0.0.0.0 means all available interfaces.
bind_address = "0.0.0.0"
# Max UDP packet size for receiver buffer
max_udp_packet_size = 1200

[media]
# Camera device index (0 is usually the default webcam)
camera_index = 0
frame_width = 1280.0
frame_height = 720.0
frame_rate = 30
# How often to send a full keyframe (IDR frame)
h264_idr_interval = 15
# Max size for one RTP payload chunk (to avoid UDP fragmentation)
rtp_max_chunk_size = 1200
# Frame SSRC
frame_ssrc = 42
# Audio SSRC
audio_ssrc = 43
# Codec details
video_payload_type = 96
video_codec_name = "H264"
clock_rate = 90000
# RTP packet version
rtp_version = 2
# SDP media line defaults
video_media_type = "video"
audio_media_type = "audio"
media_protocol = "RTP/AVP"
jitter_buffer_size = 512
#Audio details
audio_channels = 2
audio_sample_rate = 48000
audio_frame_size = 960
audio_payload_type = 111
audio_codec_name = "OPUS"

[rtcp]
# How often to send RTCP connectivity reports
report_period_millis = 1000
# How long to wait for a report before timing out
receive_limit_millis = 3000
# Number of missed reports before closing connection
retry_limit = 5

[rtp]
# Socket read timeout in milliseconds
read_timeout_millis = 3000
# RtpPacket max size supported
max_packet_size = 1200

# SDP default session-level values
[sdp]
version = 0
origin_id = 0
session_name = "-"
timing = "0 0"
connection_data_net_type = "IN"
connection_data_addr_type = "IP4"
connection_data_address = "0.0.0.0"

# ICE default candidate values
[ice]
foundation = "1"
transport = "UDP"
component_id = 1
# RFC 8445 priority preferences
host_priority_preference = 126
srflx_priority_preference = 100
host_local_preference = 65535

[server]
users_file = "src/server/data.txt"
client_server_addr = "0.0.0.0:8080"
server_client_addr = "0.0.0.0:8081"
server_private_key_file = "./tls_server/key.pem"
server_certification_file = "./tls_server/cert.pem"
server_name = "web_rtc_server"
max_amount_of_users_connected = 10

[dcep]
ack_wait_timeout_millis = 0
open_wait_timeout_millis = 0
