use std::fmt::Display;

/// Small RTCP packet enum used by the project's reporting mechanism.
///
/// This is a representation with two packet kinds
/// used for connectivity signaling: periodic
/// connectivity reports and a goodbye message.
pub enum RtcpPacket {
    /// Periodic connectivity report.
    ConnectivityReport,

    /// Goodbye message indicating the peer is closing the session.
    Goodbye,
}

impl Display for RtcpPacket {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> Result<(), std::fmt::Error> {
        match self {
            RtcpPacket::ConnectivityReport => write!(f, "CR"),
            RtcpPacket::Goodbye => write!(f, "BYE"),
        }
    }
}

impl RtcpPacket {
    /// Return a small byte representation of the packet
    pub fn as_bytes(&self) -> &'static [u8] {
        match self {
            RtcpPacket::ConnectivityReport => b"CR",
            RtcpPacket::Goodbye => b"BY",
        }
    }

    /// Parse a packet from bytes previously generated by `as_bytes`.
    pub fn from_bytes(data: &[u8]) -> Option<Self> {
        match data {
            b"CR" => Some(RtcpPacket::ConnectivityReport),
            b"BY" => Some(RtcpPacket::Goodbye),
            _ => None,
        }
    }
}
