use std::fmt::Display;

/// Small RTCP packet enum used by the project's reporting mechanism.
///
/// This is a representation with two packet kinds
/// used for connectivity signaling: periodic
/// connectivity reports and a goodbye message.
pub enum RtcpPacket {
    /// Periodic connectivity report.
    ConnectivityReport,

    /// Goodbye message indicating the peer is closing the session.
    Goodbye,
    Hello,
    Ready,
}

impl Display for RtcpPacket {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> Result<(), std::fmt::Error> {
        match self {
            Self::ConnectivityReport => write!(f, "CR"),
            Self::Goodbye => write!(f, "BYE"),
            Self::Hello => write!(f, "HELLO"),
            Self::Ready => write!(f, "READY"),
        }
    }
}

impl RtcpPacket {
    /// Return a small byte representation of the packet
    #[must_use] 
    pub const fn as_bytes(&self) -> &'static [u8] {
        match self {
            Self::ConnectivityReport => b"CR",
            Self::Goodbye => b"BY",
            Self::Hello => b"HELLO",
            Self::Ready => b"READY",
        }
    }

    /// Parse a packet from bytes previously generated by `as_bytes`.
    #[must_use] 
    pub const fn from_bytes(data: &[u8]) -> Option<Self> {
        match data {
            b"CR" => Some(Self::ConnectivityReport),
            b"BY" => Some(Self::Goodbye),
            b"HELLO" => Some(Self::Hello),
            b"READY" => Some(Self::Ready),
            _ => None,
        }
    }
}
